### ISSUE TITLE
No id_token requested and populate when using the ImplicitBrowserFlow.

### ISSUE THREAD

**Issue by simeondorelov** [dart-lang/googleapis_auth#49]
When using the browser flow, the js gapi library's authroize method is used, but only a `'response_type': 'code token'` is requested. An id_token is never requested and never later populated into the returned AccessCredentials object.

**Comment by jonasfj** [comment]
I'm not sure why we wouldn't always include `id_token` in:

https://github.com/dart-lang/googleapis_auth/blob/89b8fc22d94ae7df5eb7c7604d473afe8bc06278/lib/src/oauth2_flows/implicit.dart#L106

It may be we should accept a list of enum values for `permission`, `id_token` and `code`, so that we have parity with `gapi`...

**Comment by simeondorelov** [comment]
Isn't the id_token tied to the openid scope passed? Then again it seems that gapi authorize always returns a scopes list including openid.
